version: "3.7"

services:
  fears-service:
    image: fears-service:latest
    container_name: fears-service
    ports:
      - "11180:8080"
    depends_on:
      - database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=postgres
      - DBSERVER_NAME=database
      - DBSERVER_PORT=5432

  database:
    image: postgres:13.2
    container_name: fears-service-db
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=postgres
